### ISSUE TITLE
You could use the message 'Invalid url' 'Resource does not exist!'

### ISSUE THREAD

**Issue by yomigeek** [amaechi-chuks/Politico#44]
https://github.com/amaechi-chuks/Politico/blob/a7739550a52ece5c9d37f65d35b471911ed6e90a/server/middleware/Validator.js#L25

**Comment by yomigeek** [comment]
Rather since it's a bad request, and not a 404 error, it should something related to `the id you provided is invalid`

**Comment by amaechi-chuks** [comment]
Acknowledged and resolved
